// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// If the environment variables are not provided (e.g. local dev without .env),
// export a lightweight stub to avoid throwing an uncaught error at module load
// while still providing a helpful message when functions are called.
/* if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missingMsg = 'Supabase not configured: please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.';
  // Minimal stub with the subset of API the app uses (functions.invoke).
  export const supabase: any = {
    functions: {
      invoke: async (_name: string, _opts?: any) => {
        console.warn(missingMsg);
        return { data: null, error: new Error(missingMsg) };
      }
    }
  };
} else {
  export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} */